import { buildEquipments } from "./Equipment";
import { LicenseByName as l } from "../../data/Licenses";

/** Magick resist (MDEF) per helm, for sorting the DPS helmet dropdown. */
export const HelmMDEF: Record<string, number> = {
	"Circlet": 60,
	"Golden Skullcap": 58,
	"White Mask": 56,
	"Dueling Mask": 55,
	"Black Mask": 53,
	"Renewing Morion": 52,
	"Celebrant's Miter": 50,
	"Grand Helm": 50,
	"Crown of Laurels": 49,
	"Gold Hairpin": 47,
	"Magepower Shishak": 47,
	"Chaperon": 46,
	"Genji Helm": 46,
	"Hypnocrown": 44,
	"Gigas Hat": 43,
	"Dragon Helm": 41,
	"Gaia Hat": 41,
	"Thief's Cap": 40,
	"Giant's Helmet": 38,
	"Astrakhan Hat": 37,
	"Chakra Band": 37,
	"Platinum Helm": 35,
	"Officer's Hat": 34,
	"Black Cowl": 33,
	"Steel Mask": 32,
	"Adamant Hat": 31,
	"Diamond Helm": 29,
	"Sorcerer's Hat": 29,
	"Goggle Mask": 28,
	"Bone Helm": 26,
	"Lamia's Tiara": 25,
	"Pirate Hat": 25,
	"Close Helmet": 23,
	"Headband": 22,
	"Mage's Hat": 21,
	"Burgonet": 20,
	"Red Cap": 19,
	"Feathered Cap": 18,
	"Golden Helm": 17,
	"Green Beret": 16,
	"Lambent Hat": 15,
	"Soldier's Cap": 14,
	"Winged Helm": 14,
	"Balaclava": 12,
	"Wizard's Hat": 12,
	"Barbut": 11,
	"Calot Hat": 10,
	"Horned Hat": 10,
	"Iron Helm": 9,
	"Leather Headgear": 8,
	"Topkapi Hat": 8,
	"Sallet": 7,
	"Bronze Helm": 6,
	"Headguard": 6,
	"Pointy Hat": 6,
	"Headgear": 5,
	"Leather Helm": 5,
	"Magick Curch": 5,
	"Cotton Cap": 4,
	"Leather Cap": 4,
};
/** Defense per body armor, for sorting the DPS armor dropdown. */
export const BodyArmorDEF: Record<string, number> = {
	"Grand Armor": 67,
	"Maximillian": 64,
	"Genji Armor": 63,
	"Lordly Robes": 61,
	"Glimmering Robes": 59,
	"Brave Suit": 57,
	"Dragon Mail": 57,
	"Black Robes": 56,
	"Mirage Vest": 55,
	"Carabineer Mail": 53,
	"Rubber Suit": 53,
	"White Robes": 53,
	"Cleric's Robes": 50,
	"Minerva Bustier": 50,
	"Platinum Armor": 49,
	"Gaia Gear": 47,
	"Gigas Chestplate": 47,
	"Jade Gown": 44,
	"Mirror Mail": 44,
	"Ninja Gear": 44,
	"Maduin Gear": 41,
	"Power Vest": 41,
	"Diamond Armor": 40,
	"Barrel Coat": 38,
	"Carmagnole": 37,
	"Adamant Vest": 35,
	"Bone Mail": 35,
	"Black Garb": 33,
	"Metal Jerkin": 31,
	"Demon Mail": 30,
	"Sorcerer's Habit": 29,
	"Viking Coat": 27,
	"Enchanter's Habit": 25,
	"Shielded Armor": 25,
	"Jujitsu Gi": 23,
	"Golden Armor": 21,
	"Mage's Habit": 21,
	"Brigandine": 20,
	"Traveler's Vestment": 18,
	"Chainmail": 17,
	"Survival Vest": 17,
	"Chanter's Djellaba": 15,
	"Heavy Coat": 14,
	"Linen Cuirass": 14,
	"Windbreaker": 12,
	"Wizard's Robes": 12,
	"Iron Armor": 11,
	"Ringmail": 10,
	"Shepherd's Bolero": 10,
	"Scale Armor": 9,
	"Bronze Chestplate": 8,
	"Kilimweave Shirt": 8,
	"Bronze Armor": 7,
	"Leather Armor": 6,
	"Leather Breastplate": 6,
	"Silken Shirt": 6,
	"Chromed Leathers": 5,
	"Light Woven Shirt": 5,
	"Cotton Shirt": 4,
	"Leather Clothing": 4,
};

export const Helm = buildEquipments([
	{ name: "Leather Cap", l: l("Light Armor 1"), },
	{ name: "Headgear", l: l("Light Armor 2"), },
	{ name: "Headguard", l: l("Light Armor 2"), },
	{ name: "Leather Headgear", l: l("Light Armor 3"), },
	{ name: "Horned Hat", l: l("Light Armor 3"), },
	{ name: "Balaclava", l: l("Light Armor 4"), str: 1, },
	{ name: "Soldier's Cap", l: l("Light Armor 4"), },
	{ name: "Green Beret", l: l("Light Armor 5"), spd: 3, },
	{ name: "Red Cap", l: l("Light Armor 5"), vit: 3, },
	{ name: "Headband", l: l("Light Armor 6"), str: 2, },
	{ name: "Pirate Hat", l: l("Light Armor 6"), },
	{ name: "Goggle Mask", l: l("Light Armor 7"), },
	{ name: "Adamant Hat", l: l("Light Armor 7"), },
	{ name: "Officer's Hat", l: l("Light Armor 8"), spd: 3, },
	{ name: "Chakra Band", l: l("Light Armor 8"), str: 2, },
	{ name: "Thief's Cap", l: l("Light Armor 9"), spd: 4, },
	{ name: "Gigas Hat", l: l("Light Armor 9"), mag: 2, },
	{ name: "Chaperon", l: l("Light Armor 10"), },
	{ name: "Crown of Laurels", l: l("Light Armor 11"), },
	{ name: "Renewing Morion", l: l("Light Armor 12"), vit: 4, },
	{ name: "Dueling Mask", l: l("Light Armor 13"), str: 2, },
	{ name: "Leather Helm", l: l("Heavy Armor 1"), str: 2, },
	{ name: "Bronze Helm", l: l("Heavy Armor 1"), str: 2, },
	{ name: "Sallet", l: l("Heavy Armor 2"), str: 3, },
	{ name: "Iron Helm", l: l("Heavy Armor 2"), str: 3, },
	{ name: "Barbut", l: l("Heavy Armor 3"), str: 4, },
	{ name: "Winged Helm", l: l("Heavy Armor 3"), str: 5, spd: 3, },
	{ name: "Golden Helm", l: l("Heavy Armor 4"), str: 5, },
	{ name: "Burgonet", l: l("Heavy Armor 4"), str: 4, },
	{ name: "Close Helmet", l: l("Heavy Armor 5"), str: 5, },
	{ name: "Bone Helm", l: l("Heavy Armor 5"), str: 6, },
	{ name: "Diamond Helm", l: l("Heavy Armor 6"), str: 7, vit: 3, },
	{ name: "Steel Mask", l: l("Heavy Armor 7"), str: 7, spd: 4, },
	{ name: "Platinum Helm", l: l("Heavy Armor 8"), str: 8, },
	{ name: "Giant's Helmet", l: l("Heavy Armor 9"), str: 8, },
	{ name: "Dragon Helm", l: l("Heavy Armor 10"), str: 9, },
	{ name: "Genji Helm", l: l("Genji Armor"), str: 9, mag: 4, },
	{ name: "Magepower Shishak", l: l("Heavy Armor 11"), str: 11, mag: 5, },
	{ name: "Grand Helm", l: l("Heavy Armor 12"), str: 12, vit: 10, },
	{ name: "Cotton Cap", l: l("Mystic Armor 1"), mag: 2, },
	{ name: "Magick Curch", l: l("Mystic Armor 1"), mag: 2, },
	{ name: "Pointy Hat", l: l("Mystic Armor 2"), mag: 2, },
	{ name: "Topkapi Hat", l: l("Mystic Armor 2"), mag: 3, },
	{ name: "Calot Hat", l: l("Mystic Armor 3"), mag: 3, },
	{ name: "Wizard's Hat", l: l("Mystic Armor 3"), mag: 4, },
	{ name: "Lambent Hat", l: l("Mystic Armor 4"), mag: 4, spd: 3, },
	{ name: "Feathered Cap", l: l("Mystic Armor 4"), mag: 5, },
	{ name: "Mage's Hat", l: l("Mystic Armor 5"), mag: 5, },
	{ name: "Lamia's Tiara", l: l("Mystic Armor 5"), mag: 4, vit: 7, },
	{ name: "Sorcerer's Hat", l: l("Mystic Armor 6"), mag: 6, },
	{ name: "Black Cowl", l: l("Mystic Armor 6"), mag: 5, spd: 4, },
	{ name: "Astrakhan Hat", l: l("Mystic Armor 7"), mag: 6, },
	{ name: "Gaia Hat", l: l("Mystic Armor 7"), mag: 7, },
	{ name: "Hypnocrown", l: l("Mystic Armor 8"), str: 2, mag: 7, },
	{ name: "Gold Hairpin", l: l("Mystic Armor 8"), mag: 7, vit: 8, },
	{ name: "Celebrant's Miter", l: l("Mystic Armor 9"), mag: 6, spd: 5, },
	{ name: "Black Mask", l: l("Mystic Armor 10"), mag: 8, },
	{ name: "White Mask", l: l("Mystic Armor 11"), mag: 8, },
	{ name: "Golden Skullcap", l: l("Mystic Armor 12"), mag: 10, spd: 3, },
	{ name: "Circlet", l: l("Mystic Armor 13"), str: 2, mag: 10, },
]);

export const BodyArmor = buildEquipments([
	{ name: "Leather Clothing", l: l("Light Armor 1"), },
	{ name: "Chromed Leathers", l: l("Light Armor 2"), },
	{ name: "Leather Breastplate", l: l("Light Armor 2"), },
	{ name: "Bronze Chestplate", l: l("Light Armor 3"), },
	{ name: "Ringmail", l: l("Light Armor 3"), str: 1, },
	{ name: "Windbreaker", l: l("Light Armor 4"), },
	{ name: "Heavy Coat", l: l("Light Armor 4"), },
	{ name: "Survival Vest", l: l("Light Armor 5"), vit: 5, },
	{ name: "Brigandine", l: l("Light Armor 5"), },
	{ name: "Jujitsu Gi", l: l("Light Armor 6"), str: 2, },
	{ name: "Viking Coat", l: l("Light Armor 6"), },
	{ name: "Metal Jerkin", l: l("Light Armor 7"), },
	{ name: "Adamant Vest", l: l("Light Armor 7"), },
	{ name: "Barrel Coat", l: l("Light Armor 8"), },
	{ name: "Power Vest", l: l("Light Armor 8"), str: 2, },
	{ name: "Ninja Gear", l: l("Light Armor 9"), spd: 4, },
	{ name: "Gigas Chestplate", l: l("Light Armor 9"), mag: 2, },
	{ name: "Minerva Bustier", l: l("Light Armor 10"), },
	{ name: "Rubber Suit", l: l("Light Armor 11"), },
	{ name: "Mirage Vest", l: l("Light Armor 12"), vit: 10, spd: 10, },
	{ name: "Brave Suit", l: l("Light Armor 13"), bravery: true, },
	{ name: "Leather Armor", l: l("Heavy Armor 1"), str: 2, },
	{ name: "Bronze Armor", l: l("Heavy Armor 1"), str: 2, },
	{ name: "Scale Armor", l: l("Heavy Armor 2"), str: 3, spd: 3, },
	{ name: "Iron Armor", l: l("Heavy Armor 2"), str: 3, },
	{ name: "Linen Cuirass", l: l("Heavy Armor 3"), str: 4, },
	{ name: "Chainmail", l: l("Heavy Armor 3"), str: 3, },
	{ name: "Golden Armor", l: l("Heavy Armor 4"), str: 4, },
	{ name: "Shielded Armor", l: l("Heavy Armor 4"), str: 5, },
	{ name: "Demon Mail", l: l("Heavy Armor 5"), str: 5, vit: 3, },
	{ name: "Bone Mail", l: l("Heavy Armor 5"), str: 6, },
	{ name: "Diamond Armor", l: l("Heavy Armor 6"), str: 7, vit: 5, },
	{ name: "Mirror Mail", l: l("Heavy Armor 7"), str: 6, },
	{ name: "Platinum Armor", l: l("Heavy Armor 8"), str: 7, },
	{ name: "Carabineer Mail", l: l("Heavy Armor 9"), str: 8, mag: 2, },
	{ name: "Dragon Mail", l: l("Heavy Armor 10"), str: 8, },
	{ name: "Genji Armor", l: l("Genji Armor"), str: 9, mag: 3, },
	{ name: "Maximillian", l: l("Heavy Armor 11"), str: 9, spd: 6, },
	{ name: "Grand Armor", l: l("Heavy Armor 12"), str: 12, },
	{ name: "Cotton Shirt", l: l("Mystic Armor 1"), mag: 1, },
	{ name: "Light Woven Shirt", l: l("Mystic Armor 1"), mag: 2, },
	{ name: "Silken Shirt", l: l("Mystic Armor 2"), mag: 2, },
	{ name: "Kilimweave Shirt", l: l("Mystic Armor 2"), mag: 3, },
	{ name: "Shepherd's Bolero", l: l("Mystic Armor 3"), mag: 3, },
	{ name: "Wizard's Robes", l: l("Mystic Armor 3"), mag: 4, },
	{ name: "Chanter's Djellaba", l: l("Mystic Armor 4"), mag: 4, vit: 5, },
	{ name: "Traveler's Vestment", l: l("Mystic Armor 4"), mag: 5, },
	{ name: "Mage's Habit", l: l("Mystic Armor 5"), mag: 6, },
	{ name: "Enchanter's Habit", l: l("Mystic Armor 5"), mag: 7, vit: 10, },
	{ name: "Sorcerer's Habit", l: l("Mystic Armor 6"), mag: 8, },
	{ name: "Black Garb", l: l("Mystic Armor 6"), mag: 6, spd: 3, },
	{ name: "Carmagnole", l: l("Mystic Armor 7"), mag: 7, },
	{ name: "Maduin Gear", l: l("Mystic Armor 7"), str: 1, mag: 8, },
	{ name: "Jade Gown", l: l("Mystic Armor 8"), mag: 8, },
	{ name: "Gaia Gear", l: l("Mystic Armor 8"), mag: 8, },
	{ name: "Cleric's Robes", l: l("Mystic Armor 9"), mag: 9, },
	{ name: "White Robes", l: l("Mystic Armor 11"), mag: 10, spd: 4, holyBonus: true, },
	{ name: "Black Robes", l: l("Mystic Armor 10"), mag: 12, darkBonus: true, },
	{ name: "Glimmering Robes", l: l("Mystic Armor 12"), mag: 12, vit: 10, },
	{ name: "Lordly Robes", l: l("Mystic Armor 13"), str: 5, mag: 15, },
]);
