import { buildEquipments } from "./Equipment.ts";
import { LicenseByName as l } from "../../data/Licenses.ts";

export const Helm = buildEquipments([
	{ name: "Leather Cap", l: l("Light Armor 1"), },
	{ name: "Cotton Cap", l: l("Mystic Armor 1"), mag: 2, },
	{ name: "Headgear", l: l("Light Armor 2"), },
	{ name: "Leather Helm", l: l("Heavy Armor 1"), str: 2, },
	{ name: "Magick Curch", l: l("Mystic Armor 1"), mag: 2, },
	{ name: "Headguard", l: l("Light Armor 2"), },
	{ name: "Bronze Helm", l: l("Heavy Armor 1"), str: 2, },
	{ name: "Pointy Hat", l: l("Mystic Armor 2"), mag: 2, },
	{ name: "Sallet", l: l("Heavy Armor 2"), str: 3, },
	{ name: "Leather Headgear", l: l("Light Armor 3"), },
	{ name: "Topkapi Hat", l: l("Mystic Armor 2"), mag: 3, },
	{ name: "Iron Helm", l: l("Heavy Armor 2"), str: 3, },
	{ name: "Horned Hat", l: l("Light Armor 3"), },
	{ name: "Calot Hat", l: l("Mystic Armor 3"), mag: 3, },
	{ name: "Barbut", l: l("Heavy Armor 3"), str: 4, },
	{ name: "Balaclava", l: l("Light Armor 4"), str: 1, },
	{ name: "Wizard's Hat", l: l("Mystic Armor 3"), mag: 4, },
	{ name: "Soldier's Cap", l: l("Light Armor 4"), },
	{ name: "Winged Helm", l: l("Heavy Armor 3"), str: 5, spd: 3, },
	{ name: "Lambent Hat", l: l("Mystic Armor 4"), mag: 4, spd: 3, },
	{ name: "Green Beret", l: l("Light Armor 5"), spd: 3, },
	{ name: "Golden Helm", l: l("Heavy Armor 4"), str: 5, },
	{ name: "Feathered Cap", l: l("Mystic Armor 4"), mag: 5, },
	{ name: "Red Cap", l: l("Light Armor 5"), vit: 3, },
	{ name: "Burgonet", l: l("Heavy Armor 4"), str: 4, },
	{ name: "Mage's Hat", l: l("Mystic Armor 5"), mag: 5, },
	{ name: "Headband", l: l("Light Armor 6"), str: 2, },
	{ name: "Close Helmet", l: l("Heavy Armor 5"), str: 5, },
	{ name: "Pirate Hat", l: l("Light Armor 6"), },
	{ name: "Lamia's Tiara", l: l("Mystic Armor 5"), mag: 4, vit: 7, },
	{ name: "Bone Helm", l: l("Heavy Armor 5"), str: 6, },
	{ name: "Goggle Mask", l: l("Light Armor 7"), },
	{ name: "Diamond Helm", l: l("Heavy Armor 6"), str: 7, vit: 3, },
	{ name: "Sorcerer's Hat", l: l("Mystic Armor 6"), mag: 6, },
	{ name: "Adamant Hat", l: l("Light Armor 7"), },
	{ name: "Steel Mask", l: l("Heavy Armor 7"), str: 7, spd: 4, },
	{ name: "Black Cowl", l: l("Mystic Armor 6"), mag: 5, spd: 4, },
	{ name: "Officer's Hat", l: l("Light Armor 8"), spd: 3, },
	{ name: "Platinum Helm", l: l("Heavy Armor 8"), str: 8, },
	{ name: "Chakra Band", l: l("Light Armor 8"), str: 2, },
	{ name: "Astrakhan Hat", l: l("Mystic Armor 7"), mag: 6, },
	{ name: "Giant's Helmet", l: l("Heavy Armor 9"), str: 8, },
	{ name: "Thief's Cap", l: l("Light Armor 9"), spd: 4, },
	{ name: "Dragon Helm", l: l("Heavy Armor 10"), str: 9, },
	{ name: "Gaia Hat", l: l("Mystic Armor 7"), mag: 7, },
	{ name: "Gigas Hat", l: l("Light Armor 9"), mag: 2, },
	{ name: "Hypnocrown", l: l("Mystic Armor 8"), str: 2, mag: 7, },
	{ name: "Chaperon", l: l("Light Armor 10"), },
	{ name: "Genji Helm", l: l("Genji Armor"), str: 9, mag: 4, },
	{ name: "Magepower Shishak", l: l("Heavy Armor 11"), str: 11, mag: 5, },
	{ name: "Gold Hairpin", l: l("Mystic Armor 8"), mag: 7, vit: 8, },
	{ name: "Crown of Laurels", l: l("Light Armor 11"), },
	{ name: "Grand Helm", l: l("Heavy Armor 12"), str: 12, vit: 10, },
	{ name: "Celebrant's Miter", l: l("Mystic Armor 9"), mag: 6, spd: 5, },
	{ name: "Renewing Morion", l: l("Light Armor 12"), vit: 4, },
	{ name: "Black Mask", l: l("Mystic Armor 10"), mag: 8, },
	{ name: "Dueling Mask", l: l("Light Armor 13"), str: 2, },
	{ name: "White Mask", l: l("Mystic Armor 11"), mag: 8, },
	{ name: "Golden Skullcap", l: l("Mystic Armor 12"), mag: 10, spd: 3, },
	{ name: "Circlet", l: l("Mystic Armor 13"), str: 2, mag: 10, },
]);

export const BodyArmor = buildEquipments([
	{ name: "Leather Clothing", l: l("Light Armor 1"), },
	{ name: "Cotton Shirt", l: l("Mystic Armor 1"), mag: 1, },
	{ name: "Chromed Leathers", l: l("Light Armor 2"), },
	{ name: "Light Woven Shirt", l: l("Mystic Armor 1"), mag: 2, },
	{ name: "Leather Breastplate", l: l("Light Armor 2"), },
	{ name: "Leather Armor", l: l("Heavy Armor 1"), str: 2, },
	{ name: "Silken Shirt", l: l("Mystic Armor 2"), mag: 2, },
	{ name: "Bronze Armor", l: l("Heavy Armor 1"), str: 2, },
	{ name: "Bronze Chestplate", l: l("Light Armor 3"), },
	{ name: "Kilimweave Shirt", l: l("Mystic Armor 2"), mag: 3, },
	{ name: "Scale Armor", l: l("Heavy Armor 2"), str: 3, spd: 3, },
	{ name: "Ringmail", l: l("Light Armor 3"), str: 1, },
	{ name: "Shepherd's Bolero", l: l("Mystic Armor 3"), mag: 3, },
	{ name: "Iron Armor", l: l("Heavy Armor 2"), str: 3, },
	{ name: "Windbreaker", l: l("Light Armor 4"), },
	{ name: "Wizard's Robes", l: l("Mystic Armor 3"), mag: 4, },
	{ name: "Heavy Coat", l: l("Light Armor 4"), },
	{ name: "Linen Cuirass", l: l("Heavy Armor 3"), str: 4, },
	{ name: "Chanter's Djellaba", l: l("Mystic Armor 4"), mag: 4, vit: 5, },
	{ name: "Survival Vest", l: l("Light Armor 5"), vit: 5, },
	{ name: "Chainmail", l: l("Heavy Armor 3"), str: 3, },
	{ name: "Traveler's Vestment", l: l("Mystic Armor 4"), mag: 5, },
	{ name: "Brigandine", l: l("Light Armor 5"), },
	{ name: "Golden Armor", l: l("Heavy Armor 4"), str: 4, },
	{ name: "Mage's Habit", l: l("Mystic Armor 5"), mag: 6, },
	{ name: "Jujitsu Gi", l: l("Light Armor 6"), str: 2, },
	{ name: "Shielded Armor", l: l("Heavy Armor 4"), str: 5, },
	{ name: "Enchanter's Habit", l: l("Mystic Armor 5"), mag: 7, vit: 10, },
	{ name: "Viking Coat", l: l("Light Armor 6"), },
	{ name: "Sorcerer's Habit", l: l("Mystic Armor 6"), mag: 8, },
	{ name: "Demon Mail", l: l("Heavy Armor 5"), str: 5, vit: 3, },
	{ name: "Metal Jerkin", l: l("Light Armor 7"), },
	{ name: "Black Garb", l: l("Mystic Armor 6"), mag: 6, spd: 3, },
	{ name: "Adamant Vest", l: l("Light Armor 7"), },
	{ name: "Bone Mail", l: l("Heavy Armor 5"), str: 6, },
	{ name: "Carmagnole", l: l("Mystic Armor 7"), mag: 7, },
	{ name: "Barrel Coat", l: l("Light Armor 8"), },
	{ name: "Diamond Armor", l: l("Heavy Armor 6"), str: 7, vit: 5, },
	{ name: "Power Vest", l: l("Light Armor 8"), str: 2, },
	{ name: "Maduin Gear", l: l("Mystic Armor 7"), str: 1, mag: 8, },
	{ name: "Ninja Gear", l: l("Light Armor 9"), spd: 4, },
	{ name: "Mirror Mail", l: l("Heavy Armor 7"), str: 6, },
	{ name: "Jade Gown", l: l("Mystic Armor 8"), mag: 8, },
	{ name: "Gigas Chestplate", l: l("Light Armor 9"), mag: 2, },
	{ name: "Gaia Gear", l: l("Mystic Armor 8"), mag: 8, },
	{ name: "Platinum Armor", l: l("Heavy Armor 8"), str: 7, },
	{ name: "Minerva Bustier", l: l("Light Armor 10"), },
	{ name: "Cleric's Robes", l: l("Mystic Armor 9"), mag: 9, },
	{ name: "Rubber Suit", l: l("Light Armor 11"), },
	{ name: "Carabineer Mail", l: l("Heavy Armor 9"), str: 8, mag: 2, },
	{ name: "White Robes", l: l("Mystic Armor 11"), mag: 10, spd: 4, holyBonus: true, },
	{ name: "Mirage Vest", l: l("Light Armor 12"), vit: 10, spd: 10, },
	{ name: "Black Robes", l: l("Mystic Armor 10"), mag: 12, darkBonus: true, },
	{ name: "Brave Suit", l: l("Light Armor 13"), bravery: true, },
	{ name: "Dragon Mail", l: l("Heavy Armor 10"), str: 8, },
	{ name: "Glimmering Robes", l: l("Mystic Armor 12"), mag: 12, vit: 10, },
	{ name: "Lordly Robes", l: l("Mystic Armor 13"), str: 5, mag: 15, },
	{ name: "Genji Armor", l: l("Genji Armor"), str: 9, mag: 3, },
	{ name: "Maximillian", l: l("Heavy Armor 11"), str: 9, spd: 6, },
	{ name: "Grand Armor", l: l("Heavy Armor 12"), str: 12, },
]);
